---
all:
  children:
    mainnet_validators:
      children:
        remote:
          hosts:
            server1:
              ansible_host: <ip address>
            server2:
              ansible_host: <ip address>
              #any var from group vars:
        local:
          hosts:
            localhost:
              #any var from group vars:
              operator_name: "<neonevm_user>"
              neonevm_network: devnet
              neonevm_default_envs:
                devnet:
                  CONFIG: devnet
                  SOLANA_URL: "{{ neonevm_solana_rpc }}"
                neonevm_chains: 
                  devnet: "0xe9ac0ce"
