- name: install postgres
  template:
    src: postgres.j2
    dest: /usr/local/bin/postgres
    owner: root
    group: root
    mode: 0755
  notify:
    - restart postgres

- name: install cache postgres service
  template:
    src: postgres.service.j2
    dest: /etc/systemd/system/postgres.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postgres
    
- name: install neonevm
  template:
    src: neonevm.j2
    dest: /usr/local/bin/neonevm
    owner: root
    group: root
    mode: 0755
  notify:
    - restart neonevm

- name: install cache rpc service
  template:
    src: neonevm.service.j2
    dest: /etc/systemd/system/neonevm.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart neonevm

- name: ensure neonevm service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: neonevm
    state: started
    enabled: true

- name: ensure postgres service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: postgres
    state: started
    enabled: true
